# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements. See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Java CI with Maven

on:
  # Run CI on Pushes to "main"" or on pull requests targeting "main".
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  rat:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Maven environment (RAT)
        uses: s4u/setup-maven-action@v1.19.0
        with:
          java-version: 17
          java-distribution: adopt
          maven-version: 3.9.11

      - name: Build with Maven (RAT profile)
        run: mvn -B --no-transfer-progress -Prat -DskipTests verify -Dskip.format.code=false

  build:
    needs: rat
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        java: [17]
        # Test both Maven 3 and Maven 4
        maven: ['3.9.11', '4.0.0-rc-5']
        experimental: [false]

    steps:
      - name: Setup Maven environment (build)
        uses: s4u/setup-maven-action@v1.19.0
        with:
          java-version: ${{ matrix.java }}
          java-distribution: adopt
          maven-version: ${{ matrix.maven }}

      - name: Build with Maven
        run: mvn -B --no-transfer-progress package --file pom.xml -DCI_ENV=true verify
